name: junglecart
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas>=2.0
  - numpy>=1.25
  - matplotlib>=3.7
  - seaborn>=0.12
  - scikit-learn>=1.3
  - lifelines>=0.27
  - lifetimes>=0.11
  - pip